services:
  mysql:
    image: mysql:8.4
    container_name: koncanica_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: koncanica_digital
    ports:
      - "3306:3306"
    volumes:
      - koncanica_mysql_data:/var/lib/mysql

volumes:
  koncanica_mysql_data:
